replicaCount: 1

image:
  repository: changeme
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: changeme
env:
  DB_ENDPOINT: changeme
  DATABASE: changeme
  USERNAME: changeme
  USERPASSWORD: changeme
  CACHE_ENDPOINT: changeme

ingress:
  enabled: true
  host: changeme
  path: /
  pathType: Prefix
  entryPoint: websecure
  tls:
    enabled: true
    secretName: tls-secret
